name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build & Deploy to Cloud Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        env:
          GENERATE_SOURCEMAP: 'false'
          REACT_APP_ETH_CONTRACT_ADDRESS: ${{ secrets.ETH_CONTRACT_ADDRESS }}
          REACT_APP_BNB_CONTRACT_ADDRESS: ${{ secrets.BNB_CONTRACT_ADDRESS }}
          REACT_APP_ZKSYNC_ERA_CONTRACT_ADDRESS: ${{ secrets.ZKE_CONTRACT_ADDRESS }}
          REACT_APP_ARBITRUM_CONTRACT_ADDRESS: ${{ secrets.ARB_CONTRACT_ADDRESS }}
          REACT_APP_ETHERSCAN_API_KEY: ${{secrets.ETHERSCAN_API_KEY }}
          REACT_APP_UNSTOPPABLE_DOMAINS_API_KEY: ${{ secrets.UNSTOPPABLE_DOMAINS_API_KEY }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Google Cloud Storage
        run: gsutil -m rsync -r -d build gs://${{ vars.BUCKET_NAME }}
